### ISSUE TITLE
Dead header link for Compliance Checker

### ISSUE THREAD

**Issue by mwengren** [ioos/comt-landing#36]
Currently pointing to: https://data.ioos.us/compliance

Should point to: https://compliance.ioos.us/

**Comment by Bobfrat** [comment]
I'm not seeing this on the comt landing page (comt.ioos.us). Is that where you are looking?
<img width="1435" alt="Screen Shot 2020-04-08 at 10 35 44 AM" src="https://user-images.githubusercontent.com/5702672/78796943-0afa2b80-7985-11ea-95a2-a6944a96cfe9.png">

**Comment by mwengren** [comment]
Sorry, I think I meant to file this here instead: https://github.com/ioos/osmc/issues.  Will file new issue.
